//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRemoteData.WCFClient.AlunoProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlunoVM", Namespace="http://schemas.datacontract.org/2004/07/DemoRemoteData.WCFServer")]
    [System.SerializableAttribute()]
    public partial class AlunoVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((object.ReferenceEquals(this.DataCadastroField, value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/DemoRemoteData.Core.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DemoRemoteData.WCFClient.AlunoProxy.Aluno))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://schemas.datacontract.org/2004/07/DemoRemoteData.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class Aluno : DemoRemoteData.WCFClient.AlunoProxy.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DemoRemoteData.WCFClient.AlunoProxy.Sexo SexoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DemoRemoteData.WCFClient.AlunoProxy.Sexo Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sexo", Namespace="http://schemas.datacontract.org/2004/07/DemoRemoteData.Core.Entities")]
    public enum Sexo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Feminino = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlunoProxy.IAlunoService")]
    public interface IAlunoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ObterTodos", ReplyAction="http://tempuri.org/IAlunoService/ObterTodosResponse")]
        DemoRemoteData.WCFClient.AlunoProxy.AlunoVM[] ObterTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ObterTodos", ReplyAction="http://tempuri.org/IAlunoService/ObterTodosResponse")]
        System.Threading.Tasks.Task<DemoRemoteData.WCFClient.AlunoProxy.AlunoVM[]> ObterTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ObterPorId", ReplyAction="http://tempuri.org/IAlunoService/ObterPorIdResponse")]
        DemoRemoteData.WCFClient.AlunoProxy.Aluno ObterPorId(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ObterPorId", ReplyAction="http://tempuri.org/IAlunoService/ObterPorIdResponse")]
        System.Threading.Tasks.Task<DemoRemoteData.WCFClient.AlunoProxy.Aluno> ObterPorIdAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Adicionar", ReplyAction="http://tempuri.org/IAlunoService/AdicionarResponse")]
        DemoRemoteData.WCFClient.AlunoProxy.Aluno Adicionar(DemoRemoteData.WCFClient.AlunoProxy.Aluno aluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Adicionar", ReplyAction="http://tempuri.org/IAlunoService/AdicionarResponse")]
        System.Threading.Tasks.Task<DemoRemoteData.WCFClient.AlunoProxy.Aluno> AdicionarAsync(DemoRemoteData.WCFClient.AlunoProxy.Aluno aluno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlunoServiceChannel : DemoRemoteData.WCFClient.AlunoProxy.IAlunoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlunoServiceClient : System.ServiceModel.ClientBase<DemoRemoteData.WCFClient.AlunoProxy.IAlunoService>, DemoRemoteData.WCFClient.AlunoProxy.IAlunoService {
        
        public AlunoServiceClient() {
        }
        
        public AlunoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DemoRemoteData.WCFClient.AlunoProxy.AlunoVM[] ObterTodos() {
            return base.Channel.ObterTodos();
        }
        
        public System.Threading.Tasks.Task<DemoRemoteData.WCFClient.AlunoProxy.AlunoVM[]> ObterTodosAsync() {
            return base.Channel.ObterTodosAsync();
        }
        
        public DemoRemoteData.WCFClient.AlunoProxy.Aluno ObterPorId(int codigo) {
            return base.Channel.ObterPorId(codigo);
        }
        
        public System.Threading.Tasks.Task<DemoRemoteData.WCFClient.AlunoProxy.Aluno> ObterPorIdAsync(int codigo) {
            return base.Channel.ObterPorIdAsync(codigo);
        }
        
        public DemoRemoteData.WCFClient.AlunoProxy.Aluno Adicionar(DemoRemoteData.WCFClient.AlunoProxy.Aluno aluno) {
            return base.Channel.Adicionar(aluno);
        }
        
        public System.Threading.Tasks.Task<DemoRemoteData.WCFClient.AlunoProxy.Aluno> AdicionarAsync(DemoRemoteData.WCFClient.AlunoProxy.Aluno aluno) {
            return base.Channel.AdicionarAsync(aluno);
        }
    }
}
